version: '3.2'
services:
  nginx:
    image: 127.0.0.1:5000/nginx
    build: ./nginx
    links:
        - jupyterhub:jupyterhub
    ports:
      - "80:80"

  jupyterhub:
    image: 127.0.0.1:5000/jupyterhub
    build: ./hub
    environment:
      ## Swarm manager
      - DOCKER_HOST=dag000.science:2376
      - DOCKER_TLS_VERIFY=1
      - DOCKER_CERT_PATH=/etc/docker/certs
    volumes:
      # Bind home docker folder -> expected to contain ca.pem, cert.pem and key.pem
      # Used by the jupyterhub to instruct the docker process on the host to spawn a notebook
      # See https://docs.docker.com/engine/security/https/#other-modes for info on how to create the files
      - type: bind
        source: ~/.docker/
        target: /etc/docker/certs

  notebook:
    image: 127.0.0.1:5000/notebook
    build: ./notebook