version: '3.2'
services:
  nginx:
    image: nginx
    links:
	- jupyterhub:jupyterhub
    ports:
      - "80:80"
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  jupyterhub:
    image: nielsbohr/jupyterhub
    volumes:
      # Mount both the config file for the jupyterhub server itself and the
      # script that kills idle containers. Furthermore the base-notebook
      # notebook image config must be mounted so that jupyterhub has access
      # to it
      - ./hub/jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py:ro
      - ./hub/cull_idle_servers.py:/srv/jupyterhub/cull_idle_servers.py:ro
      # The jupyterhub service needs access to the docker daemon process
      # to launch additional notebook services from within the service itself
      - /var/run/docker.sock:/var/run/docker.sock:rw