version: '3.2'
services:
  jupyterhub:
    image: nielsbohr/jupyterhub:latest
    ports:
       - "80:8000"
    environment:
      TZ: Europe/Copenhagen
    volumes:
      # Mount both the config file for the jupyterhub server itself and the
      # script that kills idle containers. Furthermore the base-notebook
      # notebook image config must be mounted so that jupyterhub has access
      # to it
      - ./hub/jupyterhub_config.py:/etc/jupyterhub/jupyterhub_config.py:ro
      - ./hub/cull_idle_servers.py:/srv/jupyterhub/cull_idle_servers.py:ro
      # The jupyterhub service needs accces to the docker daemon process
      # to launch addtional notebook services from within the service itself
      - /var/run/docker.sock:/var/run/docker.sock:rw
    command: jupyterhub -f /etc/jupyterhub/jupyterhub_config.py
