version: '3.2'
services:
  nginx:
    image: 127.0.0.1:5000/nbi_nginx
    build: ./nginx
    links:
        - jupyterhub:jupyterhub
    ports:
      - "80:80"

  jupyterhub:
    image: 127.0.0.1:5000/nbi_jupyterhub
    build: ./nbi_jupyterhub
    environment:
      - DOCKER_HOST=bda.erda.dk:2376
      - DOCKER_TLS_VERIFY=1
      - DOCKER_CERT_PATH=/etc/docker/certs
    volumes:
      - type: bind
        source: ~/.docker/
        target: /etc/docker/certs